name: Security CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # ← Timeout global
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: docker build -t devsecure-api .
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'devsecure-api'
        format: 'table'
        exit-code: 0  # ← Ne pas bloquer sur les vulnérabilités
      
    - name: Quick security tests
      run: |
        echo "✅ Build réussi"
        echo "🔍 Scans de sécurité en cours..."
        
    - name: Detect secrets with Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        exit-code: 0  # ← Ne pas bloquer le workflow