name: Security CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build Docker image
      run: docker build -t devsecure-api .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'devsecure-api'
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: 1

    - name: Run Snyk security scan
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: devsecure-api
        args: --file=Dockerfile --severity-threshold=high
      continue-on-error: true

    - name: Detect secrets with Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        config-path: .gitleaks.toml
        report-format: sarif
        exit-code: 1

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-reports
        path: |
          trivy-results.sarif
          gitleaks-report.sarif
        retention-days: 30

    - name: Security summary
      run: |
        echo "🔒 SCANS DE SÉCURITÉ TERMINÉS"
        echo "✅ Trivy - Vulnérabilités Docker"
        echo "✅ Gitleaks - Secrets dans le code" 
        echo "⚠️  Snyk - Dépendances (nécessite token)"
        echo "📊 Rapports disponibles en téléchargement"
