name: Security CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Build and test Docker
      run: |
        echo "🔨 Building Docker image..."
        docker build -t devsecure-api .
        echo "✅ Docker build successful"

    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'devsecure-api'
        format: 'table'
        exit-code: 0

    - name: Run Gitleaks scan
      uses: gitleaks/gitleaks-action@v2
      with:
        config-path: .gitleaks.toml

    - name: Final success
      run: |
        echo "🎉 PIPELINE RÉUSSI!"
        echo "✅ Docker build"
        echo "✅ Trivy scan" 
        echo "✅ Gitleaks scan"
